### ISSUE TITLE
service.yml config

### ISSUE THREAD

**Issue by ibrasdev** [ancarebeca/FullCalendarBundle#39]
Hello,

When i add this to my services.xml my site dont run anymore, PHP error :  does not contain valid YAML

`cmr.service.listener:
        class: CMRBundle\Listener\LoadDataListener
    	tags:
       		- { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }`

Thanks

**Comment by ancarebeca** [comment]
Hi @ibrasdev, One question Is your Symfony services configuration file in xml or yml format? Because if your file is `services.xml` I don't understand why are you getting an **invalid YAML**. 

Notice that your services file has the extension `.xml` and according to the error, your Symfony project seems to be using `.yml`. 

There is an example of how you could define it using YAML: https://github.com/ancarebeca/full-calendar-example/blob/master/app/config/services.yml
